version: "3.9"
services:
  db:
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_passw
    environment:
      MYSQL_ROOT_PASSWORD: TacaP@ssword23
      MYSQL_DATABASE: test
      MYSQL_USER: oudone
      MYSQL_PASSWORD: TacaP@ssword23
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - mynetwork
  api:
    build: .
    environment:
      DB_HOST: db
      DB_USER: oudone
      DB_PASSWORD: TacaP@ssword23
      DB_DATABASE: test
    ports:
      - '5000:5000'
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
